# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a314ae6c3a966a3968bbc6251bfa5f671a18e37a391247b108c7afe227b58b2217f4e690d82fdc0e6ad76ad6322f50477028a4942a08ca9f1d1f92ddddd1169d

test:
  secret_key_base: 8b4ecd541045d07c0435737a55d3c8615c33dc7336755861f7468ab90b3524f564afed9157a335d39df8e0c6c4830ae8542ca97875c3b8dbb58c685f79daada7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
